<div class="mx-auto w-full max-w-6xl space-y-6 p-4 sm:p-6">
    <div class="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
        <div><flux:heading size="xl">{{ $college->name }}</flux:heading><flux:text>কলেজ কোড: {{ $college->code ?: 'উল্লেখ নেই' }}</flux:text></div>
        <div class="flex gap-2"><flux:button :href="route('colleges.manage')" icon="arrow-left" wire:navigate>তালিকায় ফিরুন</flux:button><flux:button variant="primary" icon="pencil-square" :href="route('colleges.edit', $college)" wire:navigate>সম্পাদনা</flux:button></div>
    </div>

    <div class="grid gap-6 lg:grid-cols-2">
        <flux:card><flux:heading size="lg">প্রাথমিক তথ্য</flux:heading><dl class="mt-4 grid grid-cols-[10rem_1fr] gap-x-4 gap-y-3 text-sm"><dt class="text-zinc-500">কলেজের ধরন</dt><dd>{{ ['government'=>'সরকারি','non_government'=>'বেসরকারি','other'=>'অন্যান্য'][$college->college_type] ?? 'অনির্ধারিত' }}</dd><dt class="text-zinc-500">অধ্যক্ষ</dt><dd>{{ $college->principal_name ?: 'অনির্ধারিত' }}</dd><dt class="text-zinc-500">শিক্ষক</dt><dd>{{ $college->teachers_count }} জন</dd><dt class="text-zinc-500">অবস্থা</dt><dd><flux:badge :color="$college->is_active ? 'green' : 'zinc'">{{ $college->is_active ? 'সক্রিয়' : 'নিষ্ক্রিয়' }}</flux:badge></dd></dl></flux:card>
        <flux:card><flux:heading size="lg">ঠিকানা ও অবস্থান</flux:heading><dl class="mt-4 grid grid-cols-[7rem_1fr] gap-x-4 gap-y-3 text-sm"><dt class="text-zinc-500">বিভাগ</dt><dd>{{ $college->division?->name ?: 'অনির্ধারিত' }}</dd><dt class="text-zinc-500">জেলা</dt><dd>{{ $college->district?->name ?: 'অনির্ধারিত' }}</dd><dt class="text-zinc-500">থানা</dt><dd>{{ $college->thana?->name ?: 'অনির্ধারিত' }}</dd><dt class="text-zinc-500">পূর্ণ ঠিকানা</dt><dd>{{ $college->address ?: 'অনির্ধারিত' }}</dd></dl></flux:card>
        <flux:card><flux:heading size="lg">কম্পিউটার ল্যাব</flux:heading>@if($college->has_computer_lab)<div class="mt-4 grid grid-cols-2 gap-4"><div class="rounded-lg bg-indigo-50 p-4 text-center dark:bg-indigo-950"><p class="text-2xl font-bold">{{ $college->desktop_count ?? 0 }}</p><flux:text>ডেস্কটপ</flux:text></div><div class="rounded-lg bg-violet-50 p-4 text-center dark:bg-violet-950"><p class="text-2xl font-bold">{{ $college->laptop_count ?? 0 }}</p><flux:text>ল্যাপটপ</flux:text></div></div><flux:text class="mt-3">ধরন: {{ ['desktop'=>'শুধু ডেস্কটপ','laptop'=>'শুধু ল্যাপটপ','both'=>'ডেস্কটপ ও ল্যাপটপ উভয়ই'][$college->lab_equipment_type] ?? 'অনির্ধারিত' }}</flux:text>@elseif($college->has_computer_lab === false)<flux:text class="mt-4">এই কলেজে কম্পিউটার ল্যাব নেই।</flux:text>@else<flux:text class="mt-4">ল্যাবের তথ্য এখনও যোগ করা হয়নি।</flux:text>@endif</flux:card>
        <flux:card><flux:heading size="lg">লেভেল, কোর্স ও বিষয়</flux:heading><div class="mt-4 grid gap-4">@forelse($college->programs as $program)<div><p class="mb-2 text-sm font-semibold">{{ ['degree'=>'ডিগ্রি','honours'=>'অনার্স','masters'=>'মাস্টার্স','professional'=>'প্রফেশনাল','other'=>'অন্যান্য'][$program->level] ?? $program->level }}</p><div class="flex flex-wrap gap-2">@foreach($program->items ?: [$program->name] as $item)<flux:badge color="indigo">{{ $item }}</flux:badge>@endforeach</div></div>@empty<flux:text>কোনো একাডেমিক প্রোগ্রাম যোগ করা হয়নি।</flux:text>@endforelse</div></flux:card>
    </div>
</div>
