<div class="mx-auto w-full max-w-7xl space-y-6 p-4 sm:p-6">
    <div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><flux:heading size="xl">কলেজ ব্যবস্থাপনা</flux:heading><flux:text>কলেজের বিস্তারিত প্রোফাইল দেখুন ও পরিচালনা করুন।</flux:text></div><flux:button variant="primary" icon="plus" :href="route('colleges.create')" wire:navigate>নতুন কলেজ তৈরি</flux:button></div>
        <flux:card class="overflow-hidden">
            <div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><flux:heading size="lg">কলেজ তালিকা</flux:heading><flux:text>মোট {{ $colleges->total() }}টি কলেজ</flux:text></div><flux:input wire:model.live.debounce.300ms="search" type="search" icon="magnifying-glass" placeholder="নাম বা কোড..." /></div>
            <div class="mt-4 overflow-x-auto"><flux:table><flux:table.columns><flux:table.column>কলেজ</flux:table.column><flux:table.column>অবস্থান</flux:table.column><flux:table.column>ধরন ও প্রোগ্রাম</flux:table.column><flux:table.column>ল্যাব</flux:table.column><flux:table.column>অধ্যক্ষ</flux:table.column><flux:table.column></flux:table.column></flux:table.columns><flux:table.rows>
                @forelse($colleges as $college)<flux:table.row wire:key="college-{{ $college->id }}"><flux:table.cell><p class="font-medium">{{ $college->name }}</p><flux:text>{{ $college->code ?: 'কোড নেই' }} · {{ $college->teachers_count }} জন শিক্ষক</flux:text></flux:table.cell><flux:table.cell>{{ $college->thana?->name }}, {{ $college->district?->name }}, {{ $college->division?->name }}<flux:text>{{ $college->address }}</flux:text></flux:table.cell><flux:table.cell>{{ ['government'=>'সরকারি','non_government'=>'বেসরকারি','other'=>'অন্যান্য'][$college->college_type] ?? 'অনির্ধারিত' }}<flux:text>{{ $college->programs->map(fn($program) => $program->level.': '.collect($program->items ?: [$program->name])->implode(', '))->implode(' · ') ?: 'প্রোগ্রাম নেই' }}</flux:text></flux:table.cell><flux:table.cell>@if($college->has_computer_lab)<span class="font-medium text-green-700 dark:text-green-400">ল্যাব আছে</span><flux:text>ডেস্কটপ {{ $college->desktop_count ?? 0 }} · ল্যাপটপ {{ $college->laptop_count ?? 0 }}</flux:text>@elseif($college->has_computer_lab === false)<span class="text-zinc-500">ল্যাব নেই</span>@else<span class="text-zinc-500">অনির্ধারিত</span>@endif</flux:table.cell><flux:table.cell>{{ $college->principal_name ?: 'অনির্ধারিত' }}</flux:table.cell><flux:table.cell><div class="flex justify-end gap-2"><flux:button size="sm" :href="route('colleges.edit', $college)" wire:navigate>সম্পাদনা</flux:button><flux:button size="sm" variant="danger" wire:click="delete({{ $college->id }})" wire:confirm="কলেজটি মুছবেন?">মুছুন</flux:button></div></flux:table.cell></flux:table.row>
                @empty<flux:table.row><flux:table.cell colspan="6" class="py-8 text-center">কোনো কলেজ নেই।</flux:table.cell></flux:table.row>@endforelse
            </flux:table.rows></flux:table></div><div class="mt-4">{{ $colleges->links() }}</div>
        </flux:card>
</div>
