<div class="mx-auto w-full max-w-6xl space-y-6 p-4 sm:p-6">
    <div class="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
        <div><flux:heading size="xl">{{ $college->name }}</flux:heading><flux:text>College code: {{ $college->code ?: __('Not provided') }}</flux:text></div>
        <div class="flex gap-2"><flux:button :href="auth()->user()->isAdmin() ? route('colleges.manage') : route('dashboard')" icon="arrow-left" wire:navigate>{{ auth()->user()->isAdmin() ? __('Back to list') : __('Back to dashboard') }}</flux:button><flux:button variant="primary" icon="pencil-square" :href="route('colleges.edit', $college)" wire:navigate>{{ __('Edit') }}</flux:button></div>
    </div>

    <div class="grid gap-6 lg:grid-cols-2">
        <flux:card><flux:heading size="lg">{{ __('Basic Information') }}</flux:heading><dl class="mt-4 grid grid-cols-[10rem_1fr] gap-x-4 gap-y-3 text-sm"><dt class="text-zinc-500">{{ __('College information') }}</dt><dd>{{ ['government'=>__('Government'),'non_government'=>__('Non-government'),'other'=>__('Other')][$college->college_type] ?? __('Not specified') }}</dd><dt class="text-zinc-500">{{ __('Principal') }}</dt><dd>{{ $college->principal_name ?: __('Not specified') }}</dd><dt class="text-zinc-500">{{ __('Email') }}</dt><dd>{{ $college->college_email ?: __('Not specified') }}</dd><dt class="text-zinc-500">{{ __('Website') }}</dt><dd>@if($college->college_website)<a href="{{ $college->college_website }}" class="text-indigo-600 hover:underline dark:text-indigo-400" target="_blank" rel="noopener noreferrer">{{ $college->college_website }}</a>@else Not specified @endif</dd><dt class="text-zinc-500">{{ __('Teacher') }}</dt><dd>{{ $college->teachers_count }} teachers</dd><dt class="text-zinc-500">{{ __('Status') }}</dt><dd><flux:badge :color="$college->is_active ? 'green' : 'zinc'">{{ $college->is_active ? __('Active') : __('Inactive') }}</flux:badge></dd></dl></flux:card>
        <flux:card><flux:heading size="lg">{{ __('Address & Location') }}</flux:heading><dl class="mt-4 grid grid-cols-[7rem_1fr] gap-x-4 gap-y-3 text-sm"><dt class="text-zinc-500">{{ __('Division') }}</dt><dd>{{ $college->division?->name ?: __('Not specified') }}</dd><dt class="text-zinc-500">{{ __('District') }}</dt><dd>{{ $college->district?->name ?: __('Not specified') }}</dd><dt class="text-zinc-500">{{ __('Thana') }}</dt><dd>{{ $college->thana?->name ?: __('Not specified') }}</dd><dt class="text-zinc-500">{{ __('Full Address') }}</dt><dd>{{ $college->address ?: __('Not specified') }}</dd></dl></flux:card>
        <flux:card><flux:heading size="lg">{{ __('Computer Lab') }}</flux:heading>@if($college->has_computer_lab)<div class="mt-4 grid grid-cols-2 gap-4"><div class="rounded-lg bg-indigo-50 p-4 text-center dark:bg-indigo-950"><p class="text-2xl font-bold">{{ $college->desktop_count ?? 0 }}</p><flux:text>{{ __('Desktop') }}</flux:text></div><div class="rounded-lg bg-violet-50 p-4 text-center dark:bg-violet-950"><p class="text-2xl font-bold">{{ $college->laptop_count ?? 0 }}</p><flux:text>{{ __('Laptop') }}</flux:text></div></div><flux:text class="mt-3">Type: {{ ['desktop'=>__('Desktop only'),'laptop'=>__('Laptop only'),'both'=>__('Both desktop and laptop')][$college->lab_equipment_type] ?? __('Not specified') }}</flux:text>@elseif($college->has_computer_lab === false)<flux:text class="mt-4">{{ __('College information') }}</flux:text>@else<flux:text class="mt-4">{{ __('Lab information') }}</flux:text>@endif</flux:card>
        <flux:card><flux:heading size="lg">{{ __('Information') }}</flux:heading><div class="mt-4 grid gap-4">@forelse($college->programs as $program)<div><p class="mb-2 text-sm font-semibold">{{ ['degree'=>__('Degree'),'honours'=>__('Honours'),'masters'=>__('Masters'),'professional'=>__('Professional'),'other'=>__('Other')][$program->level] ?? $program->level }}</p><div class="flex flex-wrap gap-2">@foreach($program->items ?: [$program->name] as $item)<flux:badge color="indigo">{{ $item }}</flux:badge>@endforeach</div></div>@empty<flux:text>{{ __('Information') }}</flux:text>@endforelse</div></flux:card>
    </div>
</div>
