<div class="mx-auto w-full max-w-7xl space-y-6 p-4 sm:p-6">
    <div><flux:heading size="xl">রোলস ও পারমিশন ম্যানেজার</flux:heading><flux:text>শিক্ষক user-কে তার অনুমোদিত কলেজের Principal অথবা Admin রোল প্রদান করুন।</flux:text></div>
    <div class="grid gap-4 md:grid-cols-3">@foreach($roles as $role)<flux:card wire:key="role-summary-{{ $role->value }}"><flux:heading size="lg">{{ $role->label() }}</flux:heading><ul class="mt-3 list-inside list-disc space-y-1 text-sm text-zinc-600 dark:text-zinc-300">@foreach($role->permissions() as $permission)<li>{{ $permission }}</li>@endforeach</ul></flux:card>@endforeach</div>
    <flux:card>
        <div class="mb-4"><flux:input wire:model.live.debounce.300ms="search" type="search" icon="magnifying-glass" placeholder="নাম বা ইমেইল দিয়ে user খুঁজুন" /></div>
        <div class="overflow-x-auto"><flux:table><flux:table.columns><flux:table.column>User</flux:table.column><flux:table.column>শিক্ষক ও কলেজ</flux:table.column><flux:table.column>বর্তমান রোল</flux:table.column><flux:table.column>রোল পরিবর্তন</flux:table.column></flux:table.columns><flux:table.rows>@foreach($users as $user)@php($teacherProfile = $user->teacher ?? $user->teacherProfile)<flux:table.row wire:key="role-user-{{ $user->id }}"><flux:table.cell><p class="font-semibold">{{ $user->name }}</p><flux:text>{{ $user->email }}</flux:text></flux:table.cell><flux:table.cell>{{ $teacherProfile?->name ?: 'শিক্ষক প্রোফাইল নেই' }}<br><flux:text>{{ $teacherProfile?->college?->name ?: $user->college?->name ?: 'কলেজ নেই' }}</flux:text></flux:table.cell><flux:table.cell><flux:badge>{{ $user->role->label() }}</flux:badge></flux:table.cell><flux:table.cell><flux:select :disabled="$user->id === auth()->id()" wire:change="changeRole({{ $user->id }}, $event.target.value)">@foreach($roles as $role)<option value="{{ $role->value }}" @selected($user->role === $role)>{{ $role->label() }}</option>@endforeach</flux:select></flux:table.cell></flux:table.row>@endforeach</flux:table.rows></flux:table></div>
        <div class="mt-4">{{ $users->links() }}</div>
    </flux:card>
</div>
