<div class="mx-auto w-full max-w-5xl space-y-6 p-4 sm:p-6">
    <div class="flex items-start justify-between gap-4"><div><flux:heading size="xl">{{ $editingId ? 'শিক্ষক প্রোফাইল সম্পাদনা' : 'নতুন শিক্ষক তৈরি' }}</flux:heading><flux:text>পেশাগত, যোগাযোগ ও ব্যাংক তথ্য সংরক্ষণ করুন। বিদ্যমান ট্রেনিং ইতিহাস অপরিবর্তিত থাকবে।</flux:text></div><flux:button :href="auth()->user()->role === \App\Enums\UserRole::Teacher ? route('dashboard') : route('teachers.manage')" icon="arrow-left" wire:navigate>ফিরে যান</flux:button></div>
    <form wire:submit="save" class="grid gap-6">
        <flux:card><flux:heading size="lg">প্রতিষ্ঠান ও পরিচিতি</flux:heading><div class="mt-4 grid gap-4 sm:grid-cols-2"><flux:select wire:model="collegeId" label="কলেজ" required><option value="">কলেজ নির্বাচন করুন</option>@foreach($colleges as $college)<option value="{{ $college->id }}">{{ $college->code ? $college->code.' — ' : '' }}{{ $college->name }}</option>@endforeach</flux:select><flux:input wire:model="name" label="শিক্ষকের নাম" required /><flux:input wire:model="birthDate" type="date" label="জন্ম তারিখ" /><flux:input wire:model="tmisId" label="TMIS ID" /><flux:field><flux:label>TTIS ID</flux:label><flux:input wire:model="ttisId" readonly placeholder="সংরক্ষণের পর স্বয়ংক্রিয়ভাবে তৈরি হবে" /><flux:description>Teachers Training Information System ID সিস্টেম থেকে স্বয়ংক্রিয়ভাবে নির্ধারিত হবে।</flux:description></flux:field></div></flux:card>
        <flux:card><flux:heading size="lg">পেশাগত তথ্য</flux:heading><div class="mt-4 grid gap-4 sm:grid-cols-2"><flux:select wire:model="designation" label="পদবি"><option value="">নির্বাচন</option>@foreach($designations as $item)<option>{{ $item }}</option>@endforeach</flux:select><flux:select wire:model="subject" label="বিষয়"><option value="">নির্বাচন</option>@foreach($subjects as $item)<option>{{ $item }}</option>@endforeach</flux:select><flux:select wire:model="teacherLevel" label="শিক্ষক স্তর"><option value="">নির্বাচন</option>@foreach($teacherLevels as $item)<option>{{ $item }}</option>@endforeach</flux:select><flux:select wire:model="employmentType" label="চাকরির ধরন"><option value="">নির্বাচন</option>@foreach($employments as $item)<option>{{ $item }}</option>@endforeach</flux:select></div></flux:card>
        <flux:card><flux:heading size="lg">যোগাযোগ ও ঠিকানা</flux:heading><div class="mt-4 grid gap-4 sm:grid-cols-3"><flux:select wire:model.live="divisionId" label="বিভাগ" required><option value="">নির্বাচন</option>@foreach($divisions as $item)<option value="{{ $item->id }}">{{ $item->name }}</option>@endforeach</flux:select><flux:select wire:model.live="districtId" label="জেলা" required><option value="">নির্বাচন</option>@foreach($districts as $item)<option value="{{ $item->id }}">{{ $item->name }}</option>@endforeach</flux:select><flux:select wire:model="thanaId" label="থানা" required><option value="">নির্বাচন</option>@foreach($thanas as $item)<option value="{{ $item->id }}">{{ $item->name }}</option>@endforeach</flux:select></div><div class="mt-4 grid gap-4 sm:grid-cols-2"><flux:textarea wire:model="presentAddress" label="বর্তমান ঠিকানা" required /><flux:textarea wire:model="permanentAddress" label="স্থায়ী ঠিকানা" required /><flux:input wire:model="mobileNumber" label="মোবাইল নম্বর" required /><flux:field><flux:label>ইমেইল ঠিকানা</flux:label><flux:input wire:model="email" type="email" :readonly="auth()->user()->role === \App\Enums\UserRole::Teacher" /><flux:description>শিক্ষক account তৈরির সময় ব্যবহৃত ইমেইল ঠিকানা।</flux:description><flux:error name="email" /></flux:field></div></flux:card>
        <flux:card>
            <div class="flex items-center justify-between gap-3"><div><flux:heading size="lg">প্রতিষ্ঠানভিত্তিক ট্রেনিং ইতিহাস</flux:heading><flux:text>নির্ধারিত অথবা অন্যান্য একাধিক ট্রেনিং যোগ করুন।</flux:text></div><flux:button type="button" size="sm" icon="plus" wire:click="addTrainingEntry">আরেকটি ট্রেনিং</flux:button></div>
            <div class="mt-4 grid gap-4">@foreach($trainingEntries as $index => $entry)<div wire:key="profile-training-{{ $index }}" class="grid gap-3 rounded-lg border border-zinc-200 p-3 dark:border-zinc-700 sm:grid-cols-2 lg:grid-cols-4"><flux:select wire:model.live="trainingEntries.{{ $index }}.kind" label="ট্রেনিং ধরন"><option value="catalog">নির্ধারিত</option><option value="other">অন্যান্য</option></flux:select><flux:select wire:model.live="trainingEntries.{{ $index }}.training_institute_id" label="প্রতিষ্ঠান"><option value="">{{ $entry['kind'] === 'other' ? 'তালিকার বাইরে' : 'নির্বাচন' }}</option>@foreach($trainingInstitutes as $institute)<option value="{{ $institute->id }}">{{ $institute->name }}</option>@endforeach</flux:select>@if($entry['kind'] === 'catalog')<flux:select wire:model="trainingEntries.{{ $index }}.training_type_id" label="ট্রেনিং"><option value="">নির্বাচন</option>@foreach($trainingTypes->where('training_institute_id', (int) $entry['training_institute_id']) as $training)<option value="{{ $training->id }}">{{ $training->name }} ({{ $training->duration_value }} {{ ['hours'=>'ঘণ্টা','days'=>'দিন','weeks'=>'সপ্তাহ','months'=>'মাস'][$training->duration_unit] ?? '' }})</option>@endforeach</flux:select>@else<flux:input wire:model="trainingEntries.{{ $index }}.name" label="অন্যান্য ট্রেনিংয়ের নাম" />@if(blank($entry['training_institute_id']))<flux:input wire:model="trainingEntries.{{ $index }}.institute_name" label="প্রতিষ্ঠানের নাম" />@endif<div class="grid grid-cols-2 gap-2"><flux:input wire:model="trainingEntries.{{ $index }}.duration_value" type="number" min="1" label="সময়কাল" /><flux:select wire:model="trainingEntries.{{ $index }}.duration_unit" label="একক"><option value="hours">ঘণ্টা</option><option value="days">দিন</option><option value="weeks">সপ্তাহ</option><option value="months">মাস</option></flux:select></div>@endif<flux:input wire:model="trainingEntries.{{ $index }}.training_year" type="number" min="1950" max="{{ date('Y') + 1 }}" label="সম্পন্নের বছর" /><div class="flex items-end"><flux:button type="button" size="sm" variant="danger" wire:click="removeTrainingEntry({{ $index }})">বাদ দিন</flux:button></div>@error("trainingEntries.$index.training_type_id")<flux:text class="text-red-600">{{ $message }}</flux:text>@enderror @error("trainingEntries.$index.name")<flux:text class="text-red-600">{{ $message }}</flux:text>@enderror</div>@endforeach</div>
        </flux:card>
        <flux:card><flux:heading size="lg">ব্যাংক তথ্য</flux:heading><div class="mt-4 grid gap-4 sm:grid-cols-2"><flux:input wire:model="bankName" label="ব্যাংকের নাম" /><flux:input wire:model="bankBranchName" label="শাখার নাম" /><flux:input wire:model="bankAccountNumber" label="ব্যাংক অ্যাকাউন্ট নম্বর" autocomplete="off" /><flux:input wire:model="bankRoutingNumber" label="রাউটিং নম্বর" inputmode="numeric" /></div></flux:card>
        <div class="flex justify-end gap-2"><flux:button :href="auth()->user()->role === \App\Enums\UserRole::Teacher ? route('dashboard') : route('teachers.manage')" wire:navigate>বাতিল</flux:button><flux:button type="submit" variant="primary">{{ $editingId ? 'প্রোফাইল আপডেট করুন' : 'শিক্ষক তৈরি করুন' }}</flux:button></div>
    </form>
</div>
