<div class="mx-auto w-full max-w-6xl space-y-6 p-4 sm:p-6">
    <div class="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><flux:heading size="xl">{{ $teacher->name }}</flux:heading><flux:text>TMIS: {{ $teacher->tmis_id ?: 'উল্লেখ নেই' }} · TTIS: {{ $teacher->ttis_id ?: 'উল্লেখ নেই' }}</flux:text></div><div class="flex gap-2"><flux:button :href="route('teachers.manage')" icon="arrow-left" wire:navigate>তালিকায় ফিরুন</flux:button><flux:button variant="primary" icon="pencil-square" :href="route('teachers.edit', $teacher)" wire:navigate>সম্পাদনা</flux:button></div></div>
    <div class="grid gap-6 lg:grid-cols-2">
        <flux:card><flux:heading size="lg">প্রতিষ্ঠান ও পেশাগত তথ্য</flux:heading><dl class="mt-4 grid grid-cols-[9rem_1fr] gap-3 text-sm"><dt class="text-zinc-500">কলেজ</dt><dd>{{ $teacher->college?->name ?: $teacher->college_name ?: 'অনির্ধারিত' }}</dd><dt class="text-zinc-500">পদবি</dt><dd>{{ $teacher->designation ?: 'অনির্ধারিত' }}</dd><dt class="text-zinc-500">বিষয়</dt><dd>{{ $teacher->subject ?: 'অনির্ধারিত' }}</dd><dt class="text-zinc-500">শিক্ষক স্তর</dt><dd>{{ $teacher->teacher_level ?: 'অনির্ধারিত' }}</dd><dt class="text-zinc-500">চাকরির ধরন</dt><dd>{{ $teacher->employment_type ?: 'অনির্ধারিত' }}</dd></dl></flux:card>
        <flux:card><flux:heading size="lg">যোগাযোগ ও ঠিকানা</flux:heading><dl class="mt-4 grid grid-cols-[9rem_1fr] gap-3 text-sm"><dt class="text-zinc-500">বিভাগ</dt><dd>{{ $teacher->division?->bn_name ?: $teacher->division?->name ?: 'অনির্ধারিত' }}</dd><dt class="text-zinc-500">জেলা</dt><dd>{{ $teacher->district?->bn_name ?: $teacher->district?->name ?: 'অনির্ধারিত' }}</dd><dt class="text-zinc-500">থানা</dt><dd>{{ $teacher->thana?->bn_name ?: $teacher->thana?->name ?: 'অনির্ধারিত' }}</dd><dt class="text-zinc-500">বর্তমান ঠিকানা</dt><dd>{{ $teacher->present_address ?: 'অনির্ধারিত' }}</dd><dt class="text-zinc-500">স্থায়ী ঠিকানা</dt><dd>{{ $teacher->permanent_address ?: 'অনির্ধারিত' }}</dd><dt class="text-zinc-500">মোবাইল</dt><dd>{{ $teacher->mobile_number ?: 'অনির্ধারিত' }}</dd><dt class="text-zinc-500">ইমেইল</dt><dd>{{ $teacher->email ?: 'অনির্ধারিত' }}</dd></dl></flux:card>
        <flux:card><flux:heading size="lg">ল্যাব ও অতিরিক্ত তথ্য</flux:heading><dl class="mt-4 grid grid-cols-[9rem_1fr] gap-3 text-sm"><dt class="text-zinc-500">কম্পিউটার ল্যাব</dt><dd>{{ $teacher->has_computer_lab === 'Yes' ? 'আছে' : ($teacher->has_computer_lab === 'No' ? 'নেই' : 'অনির্ধারিত') }}</dd><dt class="text-zinc-500">কম্পিউটার সংখ্যা</dt><dd>{{ $teacher->computer_count ?? 'অনির্ধারিত' }}</dd><dt class="text-zinc-500">ট্রেনিং অবস্থা</dt><dd>{{ $teacher->has_training ?: 'অনির্ধারিত' }}</dd></dl></flux:card>
        <flux:card><flux:heading size="lg">ব্যাংক তথ্য</flux:heading><dl class="mt-4 grid grid-cols-[9rem_1fr] gap-3 text-sm"><dt class="text-zinc-500">ব্যাংক</dt><dd>{{ $teacher->bank_name ?: 'অনির্ধারিত' }}</dd><dt class="text-zinc-500">শাখা</dt><dd>{{ $teacher->bank_branch_name ?: 'অনির্ধারিত' }}</dd><dt class="text-zinc-500">রাউটিং নম্বর</dt><dd>{{ $teacher->bank_routing_number ?: 'অনির্ধারিত' }}</dd></dl></flux:card>
        <flux:card><flux:heading size="lg">প্রতিষ্ঠানভিত্তিক ট্রেনিং ইতিহাস</flux:heading><div class="mt-4 grid gap-4">@foreach($teacher->trainingTypes as $training)<div><p class="font-medium">{{ $training->name }}</p><flux:text>{{ $training->trainingInstitute->name }} · {{ $training->pivot->training_year }} · {{ $training->duration_value }} {{ ['hours'=>'ঘণ্টা','days'=>'দিন','weeks'=>'সপ্তাহ','months'=>'মাস'][$training->duration_unit] ?? '' }}</flux:text></div>@endforeach @foreach($teacher->otherTrainings as $training)<div><p class="font-medium">{{ $training->name }} <flux:badge>অন্যান্য</flux:badge></p><flux:text>{{ $training->trainingInstitute?->name ?: $training->institute_name ?: 'প্রতিষ্ঠান অনির্ধারিত' }} · {{ $training->training_year }}</flux:text></div>@endforeach @if($teacher->trainingTypes->isEmpty() && $teacher->otherTrainings->isEmpty())<flux:text>{{ $teacher->ict_training_name ?: 'কোনো ট্রেনিং ইতিহাস নেই।' }}</flux:text>@endif</div></flux:card>
    </div>
</div>
