<div class="mx-auto w-full max-w-5xl space-y-6 p-4 sm:p-6">
    <div class="flex items-start justify-between gap-4"><div><flux:heading size="xl">{{ $editingId ? 'শিক্ষক প্রোফাইল সম্পাদনা' : 'নতুন শিক্ষক তৈরি' }}</flux:heading><flux:text>পেশাগত, যোগাযোগ ও ব্যাংক তথ্য সংরক্ষণ করুন। বিদ্যমান ট্রেনিং ইতিহাস অপরিবর্তিত থাকবে।</flux:text></div><flux:button :href="route('teachers.manage')" icon="arrow-left" wire:navigate>তালিকায় ফিরুন</flux:button></div>
    <form wire:submit="save" class="grid gap-6">
        <flux:card><flux:heading size="lg">প্রতিষ্ঠান ও পরিচিতি</flux:heading><div class="mt-4 grid gap-4 sm:grid-cols-2"><flux:select wire:model="collegeId" label="কলেজ" required><option value="">কলেজ নির্বাচন করুন</option>@foreach($colleges as $college)<option value="{{ $college->id }}">{{ $college->code ? $college->code.' — ' : '' }}{{ $college->name }}</option>@endforeach</flux:select><flux:input wire:model="name" label="শিক্ষকের নাম" required /><flux:input wire:model="tmisId" label="TMIS ID" /><flux:input wire:model="ttisId" label="TTIS ID" /></div></flux:card>
        <flux:card><flux:heading size="lg">পেশাগত তথ্য</flux:heading><div class="mt-4 grid gap-4 sm:grid-cols-2"><flux:select wire:model="designation" label="পদবি"><option value="">নির্বাচন</option>@foreach($designations as $item)<option>{{ $item }}</option>@endforeach</flux:select><flux:select wire:model="subject" label="বিষয়"><option value="">নির্বাচন</option>@foreach($subjects as $item)<option>{{ $item }}</option>@endforeach</flux:select><flux:select wire:model="teacherLevel" label="শিক্ষক স্তর"><option value="">নির্বাচন</option>@foreach($teacherLevels as $item)<option>{{ $item }}</option>@endforeach</flux:select><flux:select wire:model="employmentType" label="চাকরির ধরন"><option value="">নির্বাচন</option>@foreach($employments as $item)<option>{{ $item }}</option>@endforeach</flux:select></div></flux:card>
        <flux:card><flux:heading size="lg">যোগাযোগ ও ঠিকানা</flux:heading><div class="mt-4 grid gap-4 sm:grid-cols-3"><flux:select wire:model.live="divisionId" label="বিভাগ" required><option value="">নির্বাচন</option>@foreach($divisions as $item)<option value="{{ $item->id }}">{{ $item->bn_name ?: $item->name }}</option>@endforeach</flux:select><flux:select wire:model.live="districtId" label="জেলা" required><option value="">নির্বাচন</option>@foreach($districts as $item)<option value="{{ $item->id }}">{{ $item->bn_name ?: $item->name }}</option>@endforeach</flux:select><flux:select wire:model="thanaId" label="থানা" required><option value="">নির্বাচন</option>@foreach($thanas as $item)<option value="{{ $item->id }}">{{ $item->bn_name ?: $item->name }}</option>@endforeach</flux:select></div><div class="mt-4 grid gap-4 sm:grid-cols-2"><flux:textarea wire:model="presentAddress" label="বর্তমান ঠিকানা" required /><flux:textarea wire:model="permanentAddress" label="স্থায়ী ঠিকানা" required /><flux:input wire:model="mobileNumber" label="মোবাইল নম্বর" required /><flux:input wire:model="email" type="email" label="ইমেইল ঠিকানা" /></div></flux:card>
        <flux:card><flux:heading size="lg">ব্যাংক তথ্য</flux:heading><div class="mt-4 grid gap-4 sm:grid-cols-3"><flux:input wire:model="bankName" label="ব্যাংকের নাম" /><flux:input wire:model="bankBranchName" label="শাখার নাম" /><flux:input wire:model="bankRoutingNumber" label="রাউটিং নম্বর" inputmode="numeric" /></div></flux:card>
        <div class="flex justify-end gap-2"><flux:button :href="route('teachers.manage')" wire:navigate>বাতিল</flux:button><flux:button type="submit" variant="primary">{{ $editingId ? 'প্রোফাইল আপডেট করুন' : 'শিক্ষক তৈরি করুন' }}</flux:button></div>
    </form>
</div>
